# Generated by Django 2.2.17 on 2021-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_body', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('web_link', models.CharField(max_length=200)),
            ],
        ),
    ]
